var marvelnames=["Captain America"
,"Wolverine"
,"Iron Man" 
,"Thor"
,"Benjamin Grimm"
,"Reed Richards"
,"Hulk" 
,"Scott Summers"
,"Jonathan Storm" 
,"Henry McCoy"
,"Susan Storm"
,"Namor McKenzie" 
,"Ororo Munroe"
,"Clinton Barton"
,"Matthew Murdock" 
,"Stephen Strange"
,"Mary Jane Watson"
,"John Jonah Jameson" 
,"Robert Drake"
,"Henry Pym"
,"Charles Xavier"
,"Warren Worthington III"
,"Piotr Rasputin"
,"Wanda Maximoff"
,"Nicholas Fury" 
,"Janet van Dyne"
,"Jean Grey" 
,"Natalia Romanova"
,"Kurt Wagner"
,"Vision"
,"May Reilly"
,"Katherine Pryde"
,"Carol Danvers"
,"Jennifer Walters" 
,"Emma Frost"
,"Frank Castle" 
,"Luke Cage"
,"Rogue"
,"Conan"
,"Joseph Robertson"
,"Pietro Maximoff"
,"Hercules"
,"Victor von Doom"
,"Max Eisenhardt"
,"Elizabeth Braddock"
,"Norrin Radd" 
,"Norman Osborn"
,"Eugene Thompson"
,"Simon Williams"];
function randomName(){
    return (marvelnames[(Math.floor(Math.random()*marvelnames.length))]).split("").filter(letter => "abcdefghijklmnopqrstuvwxyz".split("").includes(letter.toLowerCase())).join('');
};
export { randomName };